% CO2SYS_calc.m

% read in cleaned merged bottle data
merged_bottle = readtable("../../data/merged_bottle_data.csv");

[CO2SYS_out,out_headers] = CO2SYS( ...
    merged_bottle.TA, ...
    merged_bottle.DIC, ...
    1, ...
    2, ...
    merged_bottle.Salnty, ...
    merged_bottle.T_degC, ...
    merged_bottle.T_degC, ...
    0, ...
    0, ...
    merged_bottle.SiO3uM, ...
    merged_bottle.PO4uM, ...
    1, ...
    15, ...
    1);

output = array2table(CO2SYS_out, ...
    "VariableNames",out_headers);

writetable(output,"../../data/CO2SYS_out.csv")