T = readtable("data\merged_bottle_data.csv");
par1type =   2;    % The first parameter supplied is of type "2", which means "DIC"
par1    = table2array(T(:, "DIC"));    % value of the first parameter
par2type =   1;    % The first parameter supplied is of type "1", which means "TA"
par2    =  table2array(T(:, "TA"));    % value of the second parameter
sal     =   table2array(T(:,  "Salnty"));    % Salinity of the sample
tempin  =   table2array(T(:, "T_degC"));    % Temperature at input conditions
tempout =    tempin;    % Temperature at output conditions
presin  =    1025*9.81*0.0001*table2array(T(:, "R_Depth"));    % Pressure    at input conditions
presout = presin;    % Pressure    at output conditions
sil     =   table2array(T(:, "SiO3uM"));    % Concentration of silicate  in the sample (in umol/kg)
po4     =    table2array(T(:, "PO4uM"));    % Concentration of phosphate in the sample (in umol/kg)
pHscale =    1;    % pH scale at which the input pH is reported ("1" means "Total Scale")
k1k2c   =    4;    % Choice of H2CO3 and HCO3- dissociation constants K1 and K2 ("4" means "Mehrbach refit")
kso4c   =    1;    % Choice of HSO4- dissociation constants KSO4 ("1" means "Dickson")
[d, dheader, dnice] = CO2SYS(par1,par2,par1type,par2type,sal,tempin,tempout,presin,presout,sil,po4,pHscale,k1k2c,kso4c);
A = array2table(d, 'VariableNames',dheader);  % convert from array to table
T1 = cat(2,T,A);   % concatenate newly calculated columns with the original data
writetable(T1, "data/merged_bottle_co2sys.csv")