---
title: "data merging and EDA"
author: "Jade"
format: html
---

```{r}
library(httr)
library(jsonlite)
library(tidyverse)
library(naniar)
```


# Access data

```{r}
bottle_data <- read_csv(here::here("data/194903-202105_Bottle.csv"),
                        locale= locale(encoding = "latin1"),
                        guess_max = Inf)

oa_data <- read_csv(here::here("data/CALCOFI_DIC_20250122_OA.csv"))

cast_data <- read_csv(here::here("data/194903-202105_Cast.csv"))
```

# Joins

```{r}
bottle_data |> glimpse()
oa_data |> glimpse()
cast_data |> glimpse()
```

```{r}
mod_cast <- cast_data |> 
  select(Cst_Cnt, Lat_Dec, Lon_Dec, Date)

bottle_complete <- left_join(bottle_data, mod_cast)

oa_data <- oa_data |> 
  mutate(Date = paste0(Month_UTC, "/", Day_UTC, "/", Year_UTC, sep = ""))

oa_data <- oa_data |> slice(-1) |> mutate(Depth = as.numeric(Depth),
                                          Latitude = as.numeric(Latitude),
                                          Longitude = as.numeric(Longitude))
```

#  Carbonate Missingness

```{r}
merged_bottle <- read_csv(here::here("data/merged_bottle_co2sys.csv"))

merged_subset <- merged_bottle |> 
  select(TA, Salnty, T_degC, DIC, Barometer, SiO3uM, PO4uM, pHin, pCO2in)

vis_miss(merged_subset)

cols_with_missing <- merged_bottle %>%
  summarise(across(everything(), ~sum(is.na(.)))) %>%
  pivot_longer(cols = everything(), names_to = "variable", values_to = "n_missing") %>%
  filter(n_missing > 1) %>%
  arrange(-n_missing) |> 
  mutate(prop_miss = n_missing / 461)

cols_with_missing
```
```{r}
library(tidyverse)

# Read in oceanographic bottle data
hydro_bottle <- read_csv(
  here::here("data/194903-202105_Bottle.csv"),
  # change encoding
  locale=locale(encoding="latin1"),
  # increase guess_max to correctly guess column types
  guess_max = Inf
)

# Read in cast data
cast_bottle <- read_csv(here::here("data/calcofi_hydro_bottle/194903-202105_Cast.csv"))

# Read in carbonate chemistry bottle data
cc_bottle <- read_csv(here::here("data/carbonate_chem_bottle.csv"))

# Drop first row (containing units) of carbonate chemistry bottle data
cc_bottle <- cc_bottle[2:nrow(cc_bottle),]

# Merge oceanographic and cast data based on Cst_Cnt (Cast Count) and Sta_ID (Station ID)
hydro_bottle <- hydro_bottle %>%
  left_join(
    cast_bottle,
    by = join_by(Cst_Cnt, Sta_ID)
  )
cc_bottle <- cc_bottle %>%
  mutate(
    Date = as.Date(
      paste(Month_UTC, Day_UTC, Year_UTC, sep = "/"),
      tryFormats = c("%m/%d/%Y")
    ),
    .before = Year_UTC
  ) %>%
  # Change column types for merging
  mutate(
    Depth = as.double(Depth)
  )

hydro_bottle <- hydro_bottle %>%
  mutate(
    Date = as.Date(Date, format = c("%m/%d/%Y"))
  )
# generate histogram of days for carb chem data
cc_bottle %>%
  select(
    Day_UTC
  ) %>%
  ggplot(
    aes(
      x = Day_UTC
    )
  ) +
  geom_histogram(bins = 31)

# generate histogram of days for hydrographic data
hydro_bottle %>%
  select(
    Date
  ) %>%
  mutate(
    day = day(Date)
  ) %>%
  ggplot(
    aes(
      x = day
    )
  ) +
  geom_histogram(
    bins = 31
  )

# get unmatched dates
unmatched_dates <- setdiff(cc_bottle$Date, intersect(cc_bottle$Date, hydro_bottle$Date)) %>% as_date()

unique_bottle <- unique(hydro_bottle$Date)
unique_cc <- unique(cc_bottle$Date)

unmatched_dates1 <- (cc_bottle |> 
  filter(!(cc_bottle$Date %in% unique_bottle)))$Date |> unique()

cc_bottle |> 
  filter(!(cc_bottle$Date %in% unique_bottle)) |> 
  nrow()


# tabulate observations with unmatched dates
cc_bottle %>%
  filter(
    Date %in% unmatched_dates
  ) %>%
  select(
    Year_UTC, Month_UTC, Day_UTC
  ) %>%
  table() %>%
  addmargins() %>%
  `[`(,,1) %>%
  formattable::formattable()

# plot of observations with unmatched dates by year, month, day
cc_bottle %>%
  filter(
    Date %in% unmatched_dates
  ) %>%
  group_by(
    Date
  ) %>%
  summarize(
    count = n(),
    Month_UTC = first(Month_UTC),
    Day_UTC = first(Day_UTC),
    Year_UTC = first(Year_UTC)
  ) %>%
  ggplot(
    aes(
      x = factor(Year_UTC),
      y = factor(Month_UTC, levels = 1:12, labels = month.abb),
      size = count
    )
  ) +
  geom_point() +
  facet_wrap(
    vars(Day_UTC)
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45)
  ) + 
  labs(
    x = "Year",
    y = "Month",
    size = "Count"
  )

```
```{r}
diff_df <- hydro_bottle |> 
  group_by(Sta_ID) |> 
  summarize(lon_diff = max(Lon_Dec) - min(Lon_Dec),
            lat_diff = max(Lat_Dec) - min(Lat_Dec))

max(diff_df$lon_diff)

cc_bottle |> 
  filter(!(Station_ID %in% unique(hydro_bottle$Sta_ID))) |> nrow()

cc_bottle |> 
  filter(!(Depth %in% unique(hydro_bottle$Depthm))) |> nrow()
```


