% CO2SYS_calc.m

% Use CO2SYS function to compute pH, pCO2, TCO2, etc. from combined bottle
% data

% read in cleaned merged bottle data
merged_bottle = readtable("../../data/merged_bottle_data.csv");

% apply CO2SYS data to appropriate variables from merged dataset
[CO2SYS_out,out_headers] = CO2SYS( ...
    merged_bottle.TA, ...
    merged_bottle.DIC, ...
    1, ...
    2, ...
    merged_bottle.Salnty, ...
    merged_bottle.T_degC, ...
    0, ...
    1025*9.81*0.0001*merged_bottle.Depth, ...
    0, ...
    merged_bottle.SiO3uM, ...
    merged_bottle.PO4uM, ...
    1, ...
    10, ...
    1);

% format output as a table
output = array2table(CO2SYS_out, ...
    "VariableNames",out_headers);

% save output to a csv file in the data folder
writetable(output,"../../data/CO2SYS_out.csv")